PartyInvites/Components/ResponseSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using PartyInvites.Models;
using PartyInvites.Models.ViewModels;
using System;
using System.Linq;
namespace PartyInvites.Components
{
    public class ResponseSummaryViewComponent : ViewComponent
    {
        private IRepository repository;
        public ResponseSummaryViewComponent(IRepository repo)
        {
            repository = repo;
        }

         public IViewComponentResult Invoke()
                {
            return View(new ResponseSummary {
                TotalResponses = repository.Responses.Count(),
                Attendees = repository.Responses.Where(r => r.WillAttend == true).Count()
            });
         }
    }
}

PartyInvites/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" asp-href-include="lib/bootstrap/dist/css/*.min.css" />
    <title>@ViewBag.Title</title>
    <style>
        .input-validation-error {
            border-color: red;
            background-color: #fee;
        }
    </style>
</head>
<body class="panel panel-default">
    <div class="panel-heading">
        <h4>
            @ViewBag.Title
            <a class="btn btn-sm btn-primary pull-right"
               asp-action="Logout" asp-controller="Account">Log Out</a>
        </h4>
    </div>
    <div class="panel-body">
        @RenderBody()
    </div>
</body>
</html>

PartyInvites/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PartyInvites</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap..css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top navbar-custom nav-hover">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="pull-left pull-left-icon" asp-controller="Home" asp-action="Index">
                    <img src="~/images/partyinvites-logo.jpeg" style="display: inline-block;">
                </a>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">PartyInvites</a>
            </div>
            <div class="navbar-collapse collapse nav-custom">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="List">People attending</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="FindResponse">Change RSVP</a></li>
                </ul>
                <div class="pull-right">
                    @await Component.InvokeAsync("ResponseSummary")
                </div>
            </div>
        </div>
    </nav>
   

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - PartyInvites</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>